version: '3.4'

services:
  postgres:
    container_name: blackthorn_ecommerce_session_db
    restart: always
    image: postgres:alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=session
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5434:5432
